var express 	= require('express')
var router 		= express.Router()
var controller 	= require('../controllers/shopBarberPanelController')

router.route('/signupbarberofshop')			.post(controller.signupBarberOfShop)
router.route('/updatebarber')			.post(controller.updateBarber)
router.route('/sendotpformobilenumchange')			.post(controller.sendOTPOnNumberForMobileNumberChange)
router.route('/verifyotpformobilenumchange')			.post(controller.verifyOtpForMobileNumberChange)
router.route('/addbarberservices')			.post(controller.addBarberServices)
router.route('/getallservicewithcategories')	.post(controller.getAllCategoriesOfShopList)
router.route('/updatebarberservice')	.post(controller.updateBarberService)
router.route('/addbarberworkinghour')	.post(controller.addBarberWorkingHour)
router.route('/barberclientrequest')	.post(controller.barberClientRequest)
router.route('/clientrequestapproval')	.post(controller.barberClientRequestApproveOrDecline)
router.route('/upcomingbookingbarber')	.post(controller.getUpcomingBookingsForBarber)
router.route('/pastbookingsbarber')	.post(controller.getPastBookingsForBarber)
router.route('/singlebookingdetail')	.post(controller.getSingleBookingDetail)
router.route('/savebarberphotourl')	.post(controller.saveBarberPhotoGallery)
router.route('/deletesinglebarberphoto')	.post(controller.deleteBarberSinglePhotoUrl)
router.route('/addbarberblocktime')	.post(controller.addBarberBlockTime)
router.route('/getfuturebarberblocktime')	.post(controller.getFutureBarberBlockTime)
router.route('/deleteblockid')	.post(controller.deleteBlockById)
router.route('/appointmentbasedondaterange')	.post(controller.getAppointementbasedOnDateRange)
router.route('/todaybarberappointments')	.post(controller.getTodayBarberBookings)
router.route('/customersofbarber')	.post(controller.getCustomersOfBarber)
router.route('/allbookingofsinglecustomer')	.post(controller.getAllAppointmentsOfSingleCustomer)

module.exports = router;